remote_theme: "jekyll/minima@1fe0fbf"
title: Planetary Remastered
author:
  name: kemalenver
  email: kemalenver+planetary@gmail.com

description: >
  Page about planetary remastered

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: solarized-light
